### ISSUE TITLE
Update for Servant 0.15

### ISSUE THREAD

**Issue by prikhi** [mpilgrem/google-maps-geocoding#1]
Hi! The stackage 13.0 LTS has been released, which includes servant v0.15. Would you be willing to update this package & your google-static-maps package to support the latest version?

Off-topic, but would you mind if I added your package to stackage?

**Comment by mpilgrem** [comment]
I would be willing to update for `servant-0.15`. It may take me a little while to turn to the update, but I would hope to do that before the New Year.

On the subject of Stackage, I've not added the package to it for a number of reasons but principally because I was not confident I could keep to the [maintainers agreement](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md).

**Comment by prikhi** [comment]
> I would be willing to update for servant-0.15. It may take me a little while to turn to the update, but I would hope to do that before the New Year.

Wonderful, though it's not urgent or anything, I was just testing out the latest stack LTS and figured I'd make an issue before I forgot about it.

> On the subject of Stackage, I've not added the package to it for a number of reasons but principally because I was not confident I could keep to the maintainers agreement.

I was thinking I would add myself as the stackage maintainer & deal with any issues about keeping it on there. Not trying to push more work on you....

**Comment by mpilgrem** [comment]
This may take longer than expected, as there is a dependency on `generics-sop >= 0.4.0.1` and, currently, I can't get that package to build on Windows 10 with GHC 8.6.3 (https://github.com/well-typed/generics-sop/issues/93).

**Comment by mpilgrem** [comment]
I have revisited the upper bounds of the dependencies but only bumped to GHC 8.6.2 (resolver `nightly-2018-12-17`) because of the Windows/GHC 8.6.3 problem, which may be a known GHC bug. That, together with some other changes, is now on Hackage.

**Comment by prikhi** [comment]
Wonderful, thanks for the quick turn around - I really appreciate it. And thanks for the great package :)

I'm running linux so I tested it with the latest stack nightly & seems to be working fine.
