### ISSUE TITLE
Upgrade to LTS 20

### ISSUE THREAD

**Issue by NorfairKing** [mpilgrem/google-maps-geocoding#2]
The base upper bound is restrictive so I cannot use this package anymore after upgrading.

**Comment by mpilgrem** [comment]
@NorfairKing, thanks for your interest in this package. `google-maps-geocoding-0.7.0.2` on Hackage has now eased that bound. When `servant-JuicyPixels` on Hackage works with GHC 9.4, I'll ease it further.

**Comment by NorfairKing** [comment]
Wow that was fast, thank you! And thanks for the package!
